### ISSUE TITLE
Visual the catalogs by agency

### ISSUE THREAD

**Issue by gbinal** [govapi/govapi.github.io#13]
- [x]  [18F List](http://18f.github.io/API-All-the-X/data/individual_apis)  - _[code](https://github.com/18F/API-All-the-X/blob/18f-pages/data/individual_apis.html)_
- [ ] Data.gov - _[open issue](https://github.com/unitedstates/APIs/issues/12)_
- [ ] ProgrammableWeb - _[open issue](https://github.com/unitedstates/APIs/issues/16)_
- [ ] APIs.io
- [ ] PublicAPIs.com - _[open issue](https://github.com/unitedstates/APIs/issues/17)_
